import { Button, VerticalBox } from "std-widgets.slint";
import { AppGlobals } from "globals.slint";

export component Counter inherits HorizontalLayout {
    in property <int> value;

    opacity: AppGlobals.state.counter_opacity;

    animate opacity {
        duration: 1000ms;
        easing: ease-in-out;
    }

    Button {
        text: "Decrease value";
        clicked => {
            AppGlobals.decrease-clicked();
        }
    }
    
    Text {
        text: "Counter: \{root.value}";
        vertical-alignment: center;
        horizontal-alignment: center;
    }

    Button {
        text: "Increase value";
        clicked => {
            AppGlobals.increase-clicked();
        }
    }
}
